@startuml
Calculator o-- AddOperation
Calculator o-- SubstractOperation
Calculator o-- MultiplyOperation
Calculator o-- DivideOperation

class Calculator {
  - addOperation : AddOperation
  - substractOperation : SubstractOperation
  - multiplyOperation : MultiplyOperation
  - divideOperation : DivideOperation
  + calculate(operation : String, firstNumber : int, secondNumber : int) : int
}

class AddOperation {
  + operate() : int
}

class SubstractOperation {
  + operate() : int
}

class MultiplyOperation {
  + operate() : int
}

class DivideOperation {
  + operate() : int
}
@enduml