@startuml
CafeLatte *-- Espresso
CafeLatte *-- Milk

class CafeLatte {
  - name : String
  - espresso : Espresso
  - milk : Milk
  + CafeLatte()
}

class Espresso {
  - name : String
  + Espresso()
}

class Milk {
  - name : String
  + Milk()
}
@enduml